### ISSUE TITLE
Information about InternalSettings

### ISSUE THREAD

**Issue by SlimeQ** [yasirkula/UnityDynamicPanels#1]
I'm making some pretty substantial changes to this code and I can't for the life of me figure out what the purpose of the `InternalSettings` design pattern is. From what I can tell it mostly just contains passthrough functions for the owning class. Why oh why is it written like this? Where did the idea come from? What does it accomplish?

**Comment by yasirkula** [comment]
It is not a pattern. InternalSettings just holds properties and functions that I'd mark as **internal** if it was a DLL. But as it is an open-source plugin, marking members as internal won't prevent game scripts from accessing those members; so I wrapped them inside InternalSettings. They are meant to be called by the plugin itself only.

**Comment by SlimeQ** [comment]
very interesting... thanks for the info. Just ripped it out
