### ISSUE TITLE
MIN_SIZE_TOLERANCE check does not account for negative numbers

### ISSUE THREAD

**Issue by SlimeQ** [yasirkula/UnityDynamicPanels#2]
This issue is pretty widespread. In the resizing logic you're doing this a lot:

```
float flexibleWidth = newSize.x - element.Size.x;
if(flexibleWidth > MIN_SIZE_TOLERANCE)
```

Which is supposed to check if our size delta is sufficiently large to warrant a change. However, this does not account for when flexibleWidth is negative... meaning you effectively can't shrink a panel using ResizeElementTo. It should check absolute value when doing this comparison. Here's my solution:

```
	private const float MIN_SIZE_TOLERANCE = 1E-4f;
        protected bool OutsideMinSizeTolerance(float f)
        {
            return Mathf.Abs(f) > MIN_SIZE_TOLERANCE;
        }
```

**Comment by yasirkula** [comment]
I always call TryChangeSizeOf for the expanding panel; i.e. if a panel is shrinking, I call TryChangeSizeOf for the panel that is on the opposite side of this panel. As far as I remember, this check happens inside ResizeElementTo (see `else if( flexibleWidth < -MIN_SIZE_TOLERANCE )`) and Panel.OnResize. Of course, there is no harm in calling OutsideMinSizeTolerance if you plan to call TryChangeSizeOf manually from your code.

**Comment by SlimeQ** [comment]
Oh, that makes sense. The reason I'm doing that is because there are some situations where I want to basically shrink a panel to Vector2.zero and have everything else fill in. So for example I have some logic set up to always force dummy panel to zero (because I never want any dead space). This usually works (after making the MIN_SIZE_TOLERANCE change) but in some edge cases it results in bad behavior. The other thing I'm doing is "hiding" panels, in which case I'm shrinking them to zero and passing over them during surrounding calculations.

Any suggestions on implementing these features? (no dead space and hidable panels)

**Comment by yasirkula** [comment]
Inside **DynamicPanelsCanvas.InitializeRootGroup**, if you change `RootPanelGroup.AddElement( dummyPanel );` to `UnanchoredPanelGroup.AddElement( dummyPanel );`, you won't have to deal with dummy panel at all. But this prevents initial docked panels from working (they will become free panels), so you'll have to tweak that code a little.

To hide a panel, I'd suggest you to simply deactivate its gameObject. But you'll have to dock the panel after reactivating it.

**Comment by yasirkula** [comment]
Now that I think about it, a better way to handle dummy panel would be to simply add `dummyPanel.Detach();` at the end of **DynamicPanelsCanvas.Start** function, instead of changing the `RootPanelGroup.AddElement( dummyPanel );` line. This way, initial docked panels will continue working.
