### ISSUE TITLE
Smaller than screen size canvas resizes at runtime

### ISSUE THREAD

**Issue by Flavelius** [yasirkula/UnityDynamicPanels#3]
If the Canvas parent has its initial size set to something else than full (see RectTransform), it gets resized on runtime setup to something that has an unwanted offset depending on the fullsize-delta before playmode:
https://imgur.com/a/O9JA2eq

**Comment by yasirkula** [comment]
Sorry for the long delay. I've fixed the issue, it will be included in the next release.
