### ISSUE TITLE
[Feature Request]Option to hide tab header in panels with only one tab.

### ISSUE THREAD

**Issue by badawim-idcc** [yasirkula/UnityDynamicPanels#7]
Amazing asset, especially for the price of free!

Would love to have an option to hide the tab header for panels that have only one tab. It would be much more pleasing to the eye. I guess it might be kind of a layout headache to do so, but would greatly appreciate it.

Thanks!

**Comment by yasirkula** [comment]
How will we able to dock that panel to some other place without the header (and thus, the tab)?

**Comment by badawim-idcc** [comment]
The tab is shown only if docked and other panels are there. 

As for the drag, it can be made draggable by clicking anywhere inside the panel instead of only on the tab.

It would be a nice to have feature, but definitely don't do it if it's too much of a hassle.

**Comment by yasirkula** [comment]
I probably won't implement this feature but thank you for the idea nevertheless 😺
